version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dragonball-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dragonball
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - "./Dump 04112023last.sql:/docker-entrypoint-initdb.d/init.sql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dragonball-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: 