name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1 # Ajusta la versión de Node.js a tu configuración
          cache: 'npm'

      - name: Create Environment File
        run: echo "${{ secrets.PROD_ENV_FILE_DRAGONBALL_API }}"  > .env

      - name: Install NestJS CLI
        run: npm install -g @nestjs/cli

      - name: Install Dependencies (Production)
        run: npm ci --omit=dev

      - name: Build App
        run: npm run build

      - name: Start App
        run: npm run start:prod # Utiliza el comando de inicio de produccióna
